### ISSUE TITLE
Initial sketches

### ISSUE THREAD

**Issue by CasiOo** [arreche/todo-react#4]
Sketches should include our basic todo-app functionality.
Initial sketches should not include users or authentication.

We need sketches for:
- List todo items
- New todo item
- Modify todo item
- Delete todo item (might be part of another sketch)

@wesharehoodies will be looking at drawing some sketches for us.

**Comment by wesharehoodies** [comment]
http://i.imgur.com/BamlSj1.png 

Here's the initial visual of how our app is gonna look like. 

Thoughts?

**Comment by CasiOo** [comment]
Fine mockup, the basics are there.

Should we split up the filtering and action buttons?
Like, have a filter row on top, and an action row on the bottom?
